git:
  depth: 5

language: node_js
# defaulting to .nvmrc specified node version which is lts/* ->  latest LTS Node.js release
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions
# https://github.com/nvm-sh/nvm#nvmrc

cache: npm

install:
  - npm install

after-install:
  - cd packages/graphql-mirage && npm run test
  - cd ../..

before-deploy:
  - cd packages/graphql-mirage-docs && npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    all_branches: true
  local_dir: packages/graphql-mirage-docs/build
  verbose: true

# safelist
branches:
  only:
    - master
    - gh-pages
