os: linux
dist: xenial

git:
  depth: 5

language: node_js
# defaulting to .nvmrc specified node version which is lts/* ->  latest LTS Node.js release
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions
# https://github.com/nvm-sh/nvm#nvmrc

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#caching-with-npm
cache: npm

before-deploy:
  - cd packages/graphql-mirage-docs && npm run build

deploy:
  provider: pages
  strategy: git
  token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  local_dir: packages/graphql-mirage-docs/build
  verbose: true
  on:
    branch: master
  edge: true # opt in to dpl v2
