# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.0
        with:
          node-version: '12'
          check-latest: true

      - run: npm install

      - run: npm install graphql@14

      - run: npm test

      - uses: codecov/codecov-action@v1
        with:
          file: ./packages/graphql-kimera/coverage/clover.xml # optional
          # flags: unittests # optional
          name: graphql-kimera # optional
          fail_ci_if_error: true # optional (default = false)
